# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-08 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('occupation', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PxS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finishposition', models.IntegerField()),
                ('totalpositions', models.IntegerField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('seasonname', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('fsd', models.DateField()),
                ('fed', models.DateField()),
                ('asd', models.DateField()),
                ('aed', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalseasons', models.IntegerField()),
                ('totaldays', models.IntegerField()),
                ('tribalwins', models.IntegerField()),
                ('individualwins', models.IntegerField()),
                ('totalwins', models.IntegerField()),
                ('totalvotesreceived', models.IntegerField()),
                ('daysonexile', models.IntegerField()),
                ('daysonredemption', models.IntegerField()),
                ('totalduelswon', models.IntegerField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Player')),
            ],
        ),
        migrations.AddField(
            model_name='pxs',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Season'),
        ),
    ]
