# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-15 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='players',
            field=models.ManyToManyField(through='webapp.PxS', to='webapp.Player'),
        ),
    ]
