# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-16 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_season_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='p_url',
            field=models.CharField(default='noplayerimg.jpg', max_length=50),
        ),
        migrations.AddField(
            model_name='season',
            name='s_url',
            field=models.CharField(default='noseasonimg.jpg', max_length=50),
        ),
    ]
