# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-30 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20160829_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pxs',
            options={'ordering': ['pid__lastname', 'pid__firstname']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='pxs',
            order_with_respect_to=None,
        ),
    ]
