# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-30 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20160830_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='daysonexile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='daysonredemption',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='totalduelswon',
            field=models.CharField(max_length=10),
        ),
    ]
